### ISSUE TITLE
Optional support for specifying the prompt

### ISSUE THREAD

**Issue by panuhorsmalahti** [cirolini/genai-code-review#17]
It would be useful to allow users to specify the prompt to add specific checks, such as "Ensure the PR contains telemetry if it's adding new UI features" and so on.

I added the prompt as optional argument in my fork here: https://github.com/panuhorsmalahti/chatgpt-github-actions - it could be quite easily polished to a PR.

**Comment by cirolini** [comment]
Add in massive v2 improvement!!!
