### ISSUE TITLE
[FEATURE] Inclusão de parâmetro para continuar PR mesmo com falha na Action

### ISSUE THREAD

**Issue by ThiagoPanini** [cirolini/genai-code-review#4]
:rocket: **_Resumo da funcionalidade solicitada:_**
Olá @cirolini, tomei a liberdade de abrir essa issue com um template que costumo usar para requisições de _features_. Primeiramente, parabéns pela iniciativa em criar essa _action._ Ao tentar utilizar a _action_ pela primeira vez em meu repositório, me deparei com uma limitação de caracteres enviados ao ChatGPT para análise e revisão.

Traceback:

```bash
Traceback (most recent call last):
  File "/main.py", line 36, in <module>
    response = openai.Completion.create(
  File "/usr/local/lib/python3.[8](https://github.com/ThiagoPanini/terraglue/actions/runs/4038680923/jobs/6942850497#step:3:9)/site-packages/openai/api_resources/completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.8/site-packages/openai/api_requestor.py", line 227, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/lib/python3.8/site-packages/openai/api_requestor.py", line 620, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.8/site-packages/openai/api_requestor.py", line 680, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: This model's maximum context length is 40[9](https://github.com/ThiagoPanini/terraglue/actions/runs/4038680923/jobs/6942850497#step:3:10)7 tokens, however you requested 5939 tokens (3891 in your prompt; [20](https://github.com/ThiagoPanini/terraglue/actions/runs/4038680923/jobs/6942850497#step:3:21)48 for the completion). Please reduce your prompt; or completion length.
```

- [Link da execução](https://github.com/ThiagoPanini/terraglue/actions/runs/4038680923/jobs/6942850497)
- [Link do PR](https://github.com/ThiagoPanini/terraglue/pull/48)

De fato, este meu repositório em questão possui arquivos com conteúdos geralmente densos e com muitas linhas. Sabendo dessa [limitação da ChatGPT em termos de caracteres](https://community.openai.com/t/invalid-request-error/33654), o pedido que se segue é:

**Existe a possibilidade de incluir algum flag na Action para não gerar erros na esteira em caso de falhas no geral?**

___
:trophy: **_Resumo sobre benefícios da nova funcionalidade:_**
Com a implementação dessa nova funcionalidade, os usuários poderiam: 
* Não ter seus PRs bloqueados por erros na utilização desta _action_
___
:books: **_Provável complexidade:_**
A melhor opção que descreve a complexidade associada a esta funcionalidade é:
- Média complexidade
___
:bulb: **_Ideias de implementação:_**
Para implementação da funcionalidade, seria possível:
- Analisar a melhor maneira de parametrizar a action com algo como `continue_if_fail`

**Comment by cirolini** [comment]
Achei ótima a ideia, mas ainda tem duas possibilidades. Trancar o arquivo ou talvez fazer split deles. Estou trabalhando em uma nova versão agora e vou ver se consigo incluir isso.

**Comment by cirolini** [comment]
Dando uma lida no assunto, acho que basta usar uma função do proprio actions `if: ${{ always() }}`

Vou documentar isso: https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions
